[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = 'qemu-system-arm -cpu cortex-m3 -machine stm32vldiscovery -nographic -kernel target/thumbv7m-none-eabi/release/bluepill-blinky -semihosting-config enable=on,target=native'

rustflags = [
  "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7m-none-eabi"
