[package]
name = "uart-demo"
version = "0.1.0"
authors = ["David Cabanis <davidcabanis@gmail.com>"]
edition = "2024"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-io = "0.7.1"
panic-halt = "1.0.0"
nb = "1.1.0"


[dependencies.stm32f1xx-hal]
version = "0.11.0"
features = ["stm32f103", ]



# Set the default for dependencies.
[profile.dev.package."*"]
opt-level = "s"

[profile.release]
codegen-units = 1
incremental = false
debug = true
lto = true
opt-level = "s"
